version: '3.3'
services:
  db:
    container_name: postgresX
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    container_name: adminerX
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8580:8080"
volumes:
  pgdata: